{{- if and .Values.controlTower.enabled .Values.controlTower.googleApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vastaya.controlTower.secretName" . }}
  labels:
    {{- include "vastaya.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-tower
type: Opaque
stringData:
  google-api-key: {{ .Values.controlTower.googleApiKey | quote }}
{{- end }}
