{{- if and .Values.spaceport.enabled .Values.spaceport.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vastaya.spaceport.name" . }}
  labels:
    {{- include "vastaya.labels" . | nindent 4 }}
    app.kubernetes.io/component: spaceport
spec:
  type: {{ .Values.spaceport.service.type }}
  ports:
    - port: {{ .Values.spaceport.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vastaya.spaceport.selectorLabels" . | nindent 4 }}
{{- end }}
